### PR TITLE
Add SPM support

### PR DESCRIPTION
**Pull request by mukesh-mt**

### CODE REVIEW

**Comment by MustaphaQadri** [comment]
Is there a reason why this is not approved and merged?

**Comment by basalphenaar** [comment]
Like @MustaphaQadri I'm also curious why this wasn't approved and merged, it works fine for our project and saves us a lot of hassle with CocoaPods!

**Review by mukeshydv — APPROVED** [review]

**Comment by basalphenaar** [comment]
Thanks @mukeshydv for the approval! Is it possible to merge it too?

**Comment by mukeshydv** [comment]
> Thanks @mukeshydv for the approval! Is it possible to merge it too?

I can’t. @mikesalvia please check

**Review by MustaphaQadri — APPROVED** [review]

**Pull request closed without merging**
